# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='user_item',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='item_id',
            field=models.ManyToManyField(to='wishlist_app.Item'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wishlist_app.User'),
        ),
    ]
