# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0002_auto_20170531_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
